### ISSUE TITLE
[Suggestion]: UI and storage rework

### ISSUE THREAD

**Issue by ColonelGerdauf** [Fuzss/echochest#10]
### Mod Loader (Optional)

⸺

### Suggestion (Required)

Currently, the echo chest acts like a regular chest minus the XP bar. That is IMO a bit cluttered, especially when taking into consideration the expected use case of the Echo Chests.

I think that instead of 24 item boxes, it could be 8x2 or 10x2. What it could be is that for each slot, there is a stack counter where people can get whole stacks of the item. Right below is the "remainder" aka modulo where the out-of-stack items are displayed, and extracted the same way, ideally one at a time. There can be a user-defined limit on the maximum number of stacks per item that can be defined.

For example, 60 ender pearls are picked up by the echo chest. It would consume only one full slot, with 3 stacks and 12 remainder pearls.

**Comment by Fuzss** [comment]
The main idea for the echo chest is the pick up mechanic for items in the area around it. 

For a chest with increased stack sizes check out my Nether Chested mod, it allows for every stack to go up to 512 instead of 64 (configurable). 

Since both concepts exist in the respective mods i don’t see a reason to merge both. Maybe just deploy an echo chest for picking up items and pipe everything into a nether chest for the increased stack size. :)

**Comment by ColonelGerdauf** [comment]
Fair, but the intent of my request is not about storage volume; that is simply a convenient side benefit of the feature.

The intent was to simplify the organization and display of the items stored. With this system, you can very quickly understand the amount of a given item, with some space between them. This is versus having a grid of slots that has a defined limit which then worsens the logistic as well as visual clutter.
